// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using yakudza_docs.Data;

#nullable disable

namespace yakudza_docs.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("yakudza_docs.Models.DishIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DishTechCardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WeightGrams")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DishTechCardId");

                    b.ToTable("DishIngredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DishTechCardId = 1,
                            Name = "Говядина",
                            WeightGrams = 300m
                        },
                        new
                        {
                            Id = 2,
                            DishTechCardId = 1,
                            Name = "Свекла",
                            WeightGrams = 200m
                        },
                        new
                        {
                            Id = 3,
                            DishTechCardId = 1,
                            Name = "Капуста",
                            WeightGrams = 150m
                        },
                        new
                        {
                            Id = 4,
                            DishTechCardId = 1,
                            Name = "Картофель",
                            WeightGrams = 200m
                        },
                        new
                        {
                            Id = 5,
                            DishTechCardId = 1,
                            Name = "Морковь",
                            WeightGrams = 100m
                        },
                        new
                        {
                            Id = 6,
                            DishTechCardId = 1,
                            Name = "Лук",
                            WeightGrams = 80m
                        },
                        new
                        {
                            Id = 7,
                            DishTechCardId = 1,
                            Name = "Томатная паста",
                            WeightGrams = 50m
                        },
                        new
                        {
                            Id = 8,
                            DishTechCardId = 1,
                            Name = "Сметана",
                            WeightGrams = 50m
                        },
                        new
                        {
                            Id = 9,
                            DishTechCardId = 2,
                            Name = "Куриное филе",
                            WeightGrams = 250m
                        },
                        new
                        {
                            Id = 10,
                            DishTechCardId = 2,
                            Name = "Картофель",
                            WeightGrams = 300m
                        },
                        new
                        {
                            Id = 11,
                            DishTechCardId = 2,
                            Name = "Морковь",
                            WeightGrams = 150m
                        },
                        new
                        {
                            Id = 12,
                            DishTechCardId = 2,
                            Name = "Яйца",
                            WeightGrams = 100m
                        },
                        new
                        {
                            Id = 13,
                            DishTechCardId = 2,
                            Name = "Огурцы маринованные",
                            WeightGrams = 100m
                        },
                        new
                        {
                            Id = 14,
                            DishTechCardId = 2,
                            Name = "Горошек консервированный",
                            WeightGrams = 80m
                        },
                        new
                        {
                            Id = 15,
                            DishTechCardId = 2,
                            Name = "Майонез",
                            WeightGrams = 120m
                        });
                });

            modelBuilder.Entity("yakudza_docs.Models.DishTechCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Image")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DishTechCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Классический украинский борщ с говядиной и сметаной",
                            Name = "Борщ"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Традиционный салат Оливье с курицей и майонезом",
                            Name = "Оливье"
                        });
                });

            modelBuilder.Entity("yakudza_docs.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("yakudza_docs.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "admin",
                            PasswordHash = new byte[] { 142, 79, 42, 59, 28, 93, 110, 127, 128, 145, 162, 179, 196, 213, 230, 247, 8, 25, 42, 59, 76, 93, 110, 127, 128, 145, 162, 179, 196, 213, 230, 247, 8, 25, 42, 59, 76, 93, 110, 127, 128, 145, 162, 179, 196, 213, 230, 247, 8, 25, 42, 59, 76, 93, 110, 127, 128, 145, 162, 179, 196, 213, 230, 247 },
                            PasswordSalt = new byte[] { 26, 43, 60, 77, 94, 111, 112, 129, 146, 163, 180, 197, 214, 231, 248, 9, 26, 43, 60, 77, 94, 111, 112, 129, 146, 163, 180, 197, 214, 231, 248, 9, 26, 43, 60, 77, 94, 111, 112, 129, 146, 163, 180, 197, 214, 231, 248, 9, 26, 43, 60, 77, 94, 111, 112, 129, 146, 163, 180, 197, 214, 231, 248, 9, 26, 43, 60, 77, 94, 111, 112, 129, 146, 163, 180, 197, 214, 231, 248, 9, 26, 43, 60, 77, 94, 111, 112, 129, 146, 163, 180, 197, 214, 231, 248, 9, 26, 43, 60, 77, 94, 111, 112, 129, 146, 163, 180, 197, 214, 231, 248, 9, 26, 43, 60, 77, 94, 111, 112, 129, 146, 163, 180, 197, 214, 231, 248, 9, 26, 43, 60, 77, 94, 111 },
                            RoleId = 2
                        },
                        new
                        {
                            Id = 2,
                            Login = "user",
                            PasswordHash = new byte[] { 122, 107, 92, 77, 62, 47, 16, 1, 242, 227, 212, 197, 182, 167, 152, 137, 122, 107, 92, 77, 62, 47, 16, 1, 242, 227, 212, 197, 182, 167, 152, 137, 122, 107, 92, 77, 62, 47, 16, 1, 242, 227, 212, 197, 182, 167, 152, 137, 122, 107, 92, 77, 62, 47, 16, 1, 242, 227, 212, 197, 182, 167, 152, 137 },
                            PasswordSalt = new byte[] { 155, 140, 125, 110, 95, 64, 49, 34, 19, 4, 245, 230, 215, 200, 185, 170, 155, 140, 125, 110, 95, 64, 49, 34, 19, 4, 245, 230, 215, 200, 185, 170, 155, 140, 125, 110, 95, 64, 49, 34, 19, 4, 245, 230, 215, 200, 185, 170, 155, 140, 125, 110, 95, 64, 49, 34, 19, 4, 245, 230, 215, 200, 185, 170, 155, 140, 125, 110, 95, 64, 49, 34, 19, 4, 245, 230, 215, 200, 185, 170, 155, 140, 125, 110, 95, 64, 49, 34, 19, 4, 245, 230, 215, 200, 185, 170, 155, 140, 125, 110, 95, 64, 49, 34, 19, 4, 245, 230, 215, 200, 185, 170, 155, 140, 125, 110, 95, 64, 49, 34, 19, 4, 245, 230, 215, 200, 185, 170 },
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("yakudza_docs.Models.DishIngredient", b =>
                {
                    b.HasOne("yakudza_docs.Models.DishTechCard", "DishTechCard")
                        .WithMany("Ingredients")
                        .HasForeignKey("DishTechCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DishTechCard");
                });

            modelBuilder.Entity("yakudza_docs.Models.User", b =>
                {
                    b.HasOne("yakudza_docs.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("yakudza_docs.Models.DishTechCard", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("yakudza_docs.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
